language: cpp
addons:
    apt:
        packages:
            - automake
            - libpulse-dev
            - libpulse-mainloop-glib0
            - libboost-program-options-dev 

script:
    - autoreconf --install
    - ./configure
    - make && sudo make install
